version: '3.8'

services:

#  mycetes:
#    build:
#      context: ../..
#      dockerfile: misc/docker/Dockerfile
#    container_name: mycetes
#    ports:
#      - "3002:3002"  # Expose the Axum app on port 3002
##    environment:
##      - STATSD_HOST=statsd:8125  # Environment variable for StatsD host and port
#    depends_on:
#      - telegraf
#    networks:
#      - monitor-mycetes-net
#      - db-mycetes-net

  db:
    image: postgres:16
    restart: always
    container_name: mycetes-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - db-mycetes-net

  influxdb:
    image: influxdb:2.7
    container_name: mycetes-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=stats
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admintoken123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - monitor-mycetes-net

  telegraf:
    build:
      context: .
      dockerfile: telegraf.Dockerfile
    image: mycetes-telegraf:local
    container_name: mycetes-telegraf
    depends_on:
      influxdb:
        condition: service_healthy
    ports:
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - monitor-mycetes-net

  grafana:
    image: grafana/grafana
    container_name: mycetes-grafana
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor-mycetes-net

volumes:
  influxdb_data:
  grafana_data:
  pg_data:

networks:
  monitor-mycetes-net:
    driver: bridge
  db-mycetes-net:
    driver: bridge