[global_tags]

[agent]
  interval = "10s"
  round_interval = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "admintoken123"
  organization = "my-org"
  bucket = "stats"

[[inputs.statsd]]
  service_address = ":8125"
  ## StatsD supports tags in the DogStatsD format (e.g., foo:1|c|#tag:value)
  datadog_extensions = true
  ## Optional: mapping for legacy statsd format
  # metric_separator = "_"
  # parse_data_dog_tags = true
