CREATE TABLE spot
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pub_id      varchar(36)      NOT NULL UNIQUE,
    name        text             NOT NULL,
    user_id     bigint           NOT NULL,
    latitude    double precision NOT NULL,
    longitude   double precision NOT NULL,
    metadata    text             NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    approved_by bigint           NULL,
    deleted     boolean          NOT NULL DEFAULT false
);
CREATE INDEX spot_lat_lon_idx ON spot (latitude, longitude);


CREATE TABLE spot_photo
(
    id          bigserial PRIMARY KEY,
    spot_id     bigint      NOT NULL,
    storage_key text        NOT NULL,
    metadata    text        NOT NULL DEFAULT '{}',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE INDEX spot_photo_spot_id_idx ON spot_photo (spot_id);
CREATE INDEX spot_photo_storage_key_idx ON spot_photo (storage_key);